import { ClueOption, ClueType } from "./types";

const clueOptions: Record<ClueType, ClueOption[]> = {
    [ClueType.EPISODES]: [
        { value: { max: 13 }, noGos: [{ type: ClueType.EPISODES }] },
        { value: { min: 20 }, noGos: [{ type: ClueType.EPISODES }] },
    ],
    [ClueType.GENRE]: [
        { value: "Action", },
        { value: "Romance", },
        { value: "Sports", }, // may not go with some studios or even female VAs ( :( )
        { value: "Slice of Life", },
        { value: "Drama", },
        { value: "Fantasy", },
        { value: "Comedy", },
        { value: "Music", },
        { value: "Sci-Fi", },
        { value: "Mystery", },
        { value: "Thriller", },
    ],
    [ClueType.STUDIO]: [
        { value: "Trigger", yearsActive: { min: 2012 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Production I.G", yearsActive: { min: 1987 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "bones", yearsActive: { min: 2000 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Kyoto Animation", yearsActive: { min: 2003 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "MADHOUSE", yearsActive: { min: 1973 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "MAPPA", yearsActive: { min: 2012 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Shaft", yearsActive: { min: 1995 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Studio Ghibli", yearsActive: { min: 1986 }, noGos: [{ type: ClueType.STUDIO }, { type: ClueType.EPISODES }, { type: ClueType.VOICE_ACTOR }] },
        { value: "Gainax", yearsActive: { min: 1981, max: 2015 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "A-1 Pictures", yearsActive: { min: 2006 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "P.A. Works", yearsActive: { min: 2008 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Sunrise", yearsActive: { min: 1972 }, noGos: [{ type: ClueType.STUDIO }] },
        { value: "Toei Animation", yearsActive: { min: 1957 }, noGos: [{ type: ClueType.STUDIO }] },
    ],
    [ClueType.VOICE_ACTOR]: [
        { value: "Yuuki Kaji", yearsActive: { min: 2004 } },
        { value: "Kenjirou Tsuda", yearsActive: { min: 1995 } },
        { value: "Mamoru Miyano", yearsActive: { min: 2001 } },
        { value: "Tomokazu Sugita", yearsActive: { min: 2000 } },
        { value: "Yuuichi Nakamura", yearsActive: { min: 2001 } },
        { value: "Yoshimasa Hosoya", yearsActive: { min: 2004 } },
        { value: "Daisuke Ono", yearsActive: { min: 2001 } },
        { value: "Kenshou Ono", yearsActive: { min: 2001 } },
        { value: "Saori Hayami", yearsActive: { min: 2007 } },
        { value: "Kana Hanazawa", yearsActive: { min: 2003 } },
        { value: "Miyuki Sawashiro", yearsActive: { min: 1999 } },
        { value: "Takehito Koyasu", yearsActive: { min: 1988 } },
        { value: "Natsuki Hanae", yearsActive: { min: 2011 } },
        { value: "Hiroshi Kamiya", yearsActive: { min: 1994 } },
        { value: "Rie Takahashi", yearsActive: { min: 2013 } },
        { value: "Nobuhiko Okamoto", yearsActive: { min: 2006 } },
        { value: "Aoi Yuuki", yearsActive: { min: 2003 } },
        { value: "Yoshitsugu Matsuoka", yearsActive: { min: 2011 } },
        { value: "Junichi Suwabe", yearsActive: { min: 1995 } },
        { value: "Kouki Uchiyama", yearsActive: { min: 2003 } },
        { value: "Nobunaga Shimazaki", yearsActive: { min: 2010 } },
        { value: "Yuuma Uchida", yearsActive: { min: 2012 } },
        { value: "Maaya Uchida", yearsActive: { min: 2010 } },
        { value: "Jun Fukuyama", yearsActive: { min: 2000 } },
        { value: "Takahiro Sakurai", yearsActive: { min: 1996 } },
        { value: "Kaito Ishikawa", yearsActive: { min: 2010 } },
        { value: "Kouki Uchiyama", yearsActive: { min: 2003 } },
        { value: "Ryouhei Kimura", yearsActive: { min: 2002 } },
        { value: "Atsumi Tanezaki", yearsActive: { min: 2008 } },
        { value: "Ai Kayano", yearsActive: { min: 2010 } },
        { value: "Akira Ishida", yearsActive: { min: 1989 } },
        { value: "Megumi Ogata", yearsActive: { min: 1992 } },
        { value: "Yuuki Ono", yearsActive: { min: 2006 } },
        { value: "Hiro Shimono", yearsActive: { min: 2001 } },
        { value: "Romi Park", yearsActive: { min: 1997 } },
        { value: "Jouji Nakata", yearsActive: { min: 1988 } },
        { value: "Akio Ootsuka", yearsActive: { min: 1988 } },
        { value: "Shinichirou Miki", yearsActive: { min: 1989 } },
        { value: "Hikaru Midorikawa", yearsActive: { min: 1988 } }
    ],
    [ClueType.YEAR]: [
        { value: { max: 2000 }, noGos: [{ type: ClueType.YEAR }] },
        { value: { min: 2000, max: 2010 }, noGos: [{ type: ClueType.YEAR }] },
        { value: { min: 2010, max: 2020 }, noGos: [{ type: ClueType.YEAR }] },
        { value: { min: 2020 }, noGos: [{ type: ClueType.YEAR }] },
    ],
    [ClueType.WORDS_IN_TITLE]: [
        { value: { number: 1 }, noGos: [{ type: ClueType.WORDS_IN_TITLE }] },
        { value: { min: 3 }, noGos: [{ type: ClueType.WORDS_IN_TITLE }] },
        { value: { max: 3 }, noGos: [{ type: ClueType.WORDS_IN_TITLE }] },
    ],
    [ClueType.FIRST_LETTER]: [
        { value: { min: 'A', max: 'I'}, noGos: [{ type: ClueType.FIRST_LETTER }] },
        { value: { min: 'J', max: 'Q'}, noGos: [{ type: ClueType.FIRST_LETTER }] },
        { value: { min: 'R', max: 'Z'}, noGos: [{ type: ClueType.FIRST_LETTER }] },
    ],
    [ClueType.TAG]: [
        { value: "Shoujo", noGos: [{ type: ClueType.SOURCE, value: "ORIGINAL" }, { type: ClueType.TAG, value: "Shounen" },{ type: ClueType.TAG, value: "Seinen" }, { type: ClueType.TAG, value: "Josei" }, ] },
        { value: "Shounen", noGos: [{ type: ClueType.SOURCE, value: "ORIGINAL" }, { type: ClueType.TAG, value: "Shoujo" },{ type: ClueType.TAG, value: "Seinen" }, { type: ClueType.TAG, value: "Josei" },] },
        { value: "Josei", noGos: [{ type: ClueType.SOURCE, value: "ORIGINAL" }, { type: ClueType.TAG, value: "Shounen" },{ type: ClueType.TAG, value: "Seinen" }, { type: ClueType.TAG, value: "Shoujo" },] },
        { value: "Seinen", noGos: [{ type: ClueType.SOURCE, value: "ORIGINAL" }, { type: ClueType.TAG, value: "Shounen" },{ type: ClueType.TAG, value: "Shoujo" }, { type: ClueType.TAG, value: "Josei" },] },
    ],
    [ClueType.FORMAT]: [
        { value: "MOVIE", noGos: [{ type: ClueType.EPISODES }] },
    ],
    [ClueType.SOURCE]: [
        { value: "ORIGINAL", },
    ],
}

export default clueOptions;